site_name: Tests My Docs
site_description: Tests my documentation
site_author: tests team
site_dir: docs-dir
theme: 'readthedocs'
repo_url: https://github.com/galitf/test_doc.git
repo_name: GitHub
pages:
  - HOME: 'index.md'
  - README: 'README.md'
  - FAQ: 'FAQ.md'
