site_name: oVirt System Tests Docs
site_description: oVirt system tests documentation
site_author: oVirt system tests team
site_dir: docs-out
theme: readthedocs
repo_url: https://gerrit.ovirt.org/ovirt-system-tests
repo_name: Gerrit
nav:
  - README: 'README.md'
  - FAQ: 'FAQ.md'
